name = "MINLPLib"
uuid = "c36e90e8-916a-50a6-1234-075b64ef4655"
authors = ["Site Wang, Harsha Nagarajan and contributors"]
version = "0.1.0"

[deps]
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"

[compat]
Glob = "1"
JuMP = "^0.21.0"
julia = "^1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
